### ISSUE TITLE
Pings are broken

### ISSUE THREAD

**Issue by lostdoge08** [royal0959/R2NectarReworkMod#2]
Title describes it, whenever I have this mod enabled, pinging interactables show no text or popups, just a buggy name if you pinged an enemy or the ground beforehand.

**Comment by itsyourimp** [comment]
I second this one, though I wish to clarify:

- Pinging behavior for the terrain and enemies works correctly
- It's when you ping anything else (Chests, Newt Altars, interactables like the pressure plates in the Abandoned Aqueduct, Shrines, and the like) where things get odd, where the ping is essentially ephemera: having the ping color of the previous ping as Doge said, as well as not prompting a chat message or showing the ping icon

I don't wholly know why this could be- i initially blamed Wolfo's visual QoL mod but lo and behold, disabling Growth Nectar made the other work flawlessly.
